// Generated by CoffeeScript 1.6.1
(function () {

    head.js({
        jquery: "lib/jquery.min.js"
    }, {
        uuid: "lib/uuid.js"
    }, {
        namespace: "lib/namespace.min.js"
    }, {
        angular: "lib/angular/angular-1.0.0rc10.js"
    }, {
        cafetownsend: "js/CafeTownsend.js"
    });

    head.ready("cafetownsend", function () {
        var makeEventDirective;
        makeEventDirective = (function (fnName) {
            return (function () {
                return mindspace.angular.directive.EventDirectives[fnName];
            });
        });
        return angular.module('CafeTownsend', []).config([
            '$routeProvider', function ($routeProvider) {
                return $routeProvider.when('/login', {
                    template: "views/login.html",
                    controller: mindspace.cafetownsend.controller.LoginController
                }).when('/employee', {
                    template: "views/employees.html",
                    controller: mindspace.cafetownsend.controller.EmployeeController
                }).when('/employee/:id', {
                    template: "views/employee_edit.html",
                    controller: mindspace.cafetownsend.controller.EmployeeEditController
                }).otherwise({
                    redirectTo: '/employee'
                });
            }
        ]).directive('ngDblclick', makeEventDirective("dblClick")).directive('ngFocus', makeEventDirective("focus")).factory("sessionService", [
            '$log', function ($log) {
                return new mindspace.cafetownsend.service.SessionService($log);
            }
        ]).factory("employeeManager", [
            '$http', '$q', '$log', function ($http, $q, $log) {
                return new mindspace.cafetownsend.service.EmployeeManager($http, $q, $log);
            }
        ]).run(mindspace.cafetownsend.CafeTownsendApp);
    });

}).call(this);
